### ISSUE TITLE
adding event

### ISSUE THREAD

**Issue by colourful-land** [Swoorup/eth-batcher-contracts#6]
the event must highlight the type of currency received and forward. because this whole thing is designed to be atomic (if a beneficiary reverted - that can only happen if it is a contract - the whole call is reverted), I think only one event is needed for a transaction

**Comment by Swoorup** [comment]
Would this suffice? @colourful-land 

```javascript
// eth payments
  event EtherPaymentSent(
    uint256 indexed totalAmount,
    address indexed payer
  );
// token payments
  event TokenPaymentSent(
    address indexed token,
    uint256 indexed totalAmount,
    address indexed payer
  );
```

**Comment by foxgem** [comment]
Hello @Swoorup can we include all arguments passed to these two methods in the events emitted? Because, we have a logic depends on it, the proposed event definitions are not enough.

Here is the scenario I want to implemented:

When calling `sendEtherToMultipleBeneficiaries`, the callback method and data is like this: `remix(uint256 commitmentId, bytes memory nftAttestation)` which is on the target contract (AlchemyRetort.sol).

I want to track the events emitted by remix and sendEtherToMultipleBeneficiaries, at the same time, since the remix can be called by this `SplitSend.sol` and `AlchemyRetort.sol`. I want to know the what the `remix` events I got are caused by `SplitSend.sol` and what not.

If the events emitted by `sendEtherToMultipleBeneficiaries` can include all arguments used by `remix`, then this task is simple: for each event I capture, the event data includes `remix` and the data passed to `sendEtherToMultipleBeneficiaries` has the same value as the one used in `remix` method. Then I know these two events happened in one tx.

The whole flow:

1. calling `sendEtherToMultipleBeneficiaries`, pass `remix(123, ...)`
2. `sendEtherToMultipleBeneficiaries` will call `remix` on the AlchemyRetort.sol
3. `remix` event emitted when remix succeed, '123' is included in the event  <-- from AlchemyRetort.sol
4. sendEtherToMultipleBeneficiaries emit event xxx, include all target arguments 

Also, I like the idea that using different event name for paying with eth and paying with erc20.

So, how about the events can be like this:

```
event EtherPaymentSent(
    address indexed targetContract,
    bytes calldata indexed targetMessage,
    Payment[] calldata indexed _payments
  );

event TokenPaymentSent(
    address indexed targetContract,
   bytes calldata indexed targetMessage,
   address indexed tokenAddress,
   Payment[] calldata indexed _payments
  );
```

I'm not the expert of solidity, so don't know if I'm right: `targetMessage` and `_payments` can be indexed and included in an event?

if not, please include the `targetContract` and `tokenAddress` in these events, it is the most information I care about. then I use these information as a filter and get other arguments from tx input data.

Thanks.

**Comment by Swoorup** [comment]
@foxgem Wouldn't it be more reasonable to instead have event per beneficiary instead of having it in the array? Afaik indexing is meant to make it searchable. Not sure indexing on array is of benefit.

**Comment by foxgem** [comment]
@Swoorup you are right, indexing on _payments is not very helpful, you can just remove the `indexed` on `_payments`

However, I don't want to tracking each payment of donation, just the whole one is ok, I only care about if `sendEtherToMultipleBeneficiaries` is successful.

As I mentioned in my last comment, you can just include `targetContract` and `tokenAddress` in Event. These two values will be used as a filter to help me know which contract was called by `SplitSend.sol`.

**Comment by Swoorup** [comment]
To confirm I have got the following: 

```javascript
  /*
  * @dev Emitted on end of ether split payment transaction
  */
  event EtherPaymentSent(
    address targetContract,
    bytes targetMessage,
    address indexed payer,
    uint256 indexed totalAmount
  );

  /*
  * @dev Emitted on end of ERC20 split payment transaction
  */
  event TokenPaymentSent(
    address targetContract,
    bytes targetMessage,
    address indexed token,
    address indexed payer,
    uint256 indexed totalAmount
  );
```

Btw solidity only allows indexed parameters upto 3 in events. I am continuing to add some testing to support this.

**Comment by Swoorup** [comment]
@foxgem and @colourful-land Updated https://github.com/Swoorup/eth-batcher-contracts/pull/8/files 

this should cover this issue.

**Comment by Swoorup** [comment]
Merging the PR, let me know if there is anything I missed.
